import Head from 'next/head'
import Format from '../layout/format'

// components
import Section1 from '../components/section1'
import Section2 from '../components/section2'
import Section3 from '../components/section3'
import Section4 from '../components/section4'

export default function Home() {
  return (
    <Format>
      <Head>
        <title>Rhoses Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <Section1 />
      <Section2 />
      <Section3 />
      <Section4 />
    </Format>
  )
}
